### ISSUE TITLE
There is no current event loop in thread 'MainThread'.` error

### ISSUE THREAD

**Issue by rockem** [rockem/busypie#29]
```
[2020/07/06 16:19:46.494] [ERROR] Exception in main context.
Traceback (most recent call last):
  File "/home/csr_user/csr_e2e_tests/modules/logging/logging.py", line 7, in wrapper
    return func(*args, **kwargs)
  File "features/steps/insert_catalog.py", line 10, in step_impl
    assert catalog_updated(config["General"]["Base"], barcodes)
  File "/home/csr_user/csr_e2e_tests/modules/catalog.py", line 37, in catalog_updated
    wait().until(lambda: are_all_existing_barcodes_equal_to(base_ip, barcodes))
  File "/home/csr_user/csr_e2e_tests/venv/lib/python3.8/site-packages/busypie/condition.py", line 48, in until
    return asyncio.get_event_loop().run_until_complete(self._wait_for(func, lambda f: f()))
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
    And I insert catalog                                                    # modules/logging/logging.py:5 0.615s
      Traceback (most recent call last):
        File "/home/csr_user/csr_e2e_tests/venv/lib/python3.8/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/csr_user/csr_e2e_tests/venv/lib/python3.8/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "/home/csr_user/csr_e2e_tests/modules/logging/logging.py", line 7, in wrapper
          return func(*args, **kwargs)
        File "features/steps/insert_catalog.py", line 10, in step_impl
          assert catalog_updated(config["General"]["Base"], barcodes)
        File "/home/csr_user/csr_e2e_tests/modules/catalog.py", line 37, in catalog_updated
          wait().until(lambda: are_all_existing_barcodes_equal_to(base_ip, barcodes))
        File "/home/csr_user/csr_e2e_tests/venv/lib/python3.8/site-packages/busypie/condition.py", line 48, in until
          return asyncio.get_event_loop().run_until_complete(self._wait_for(func, lambda f: f()))
        File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
          raise RuntimeError('There is no current event loop in thread %r.'
      RuntimeError: There is no current event loop in thread 'MainThread'.
```

**Comment by AmosHason** [comment]
On it.
